In [1]:
import numpy as np
from sklearn.mixture import GaussianMixture

# Example usage:
if __name__ == "__main__":
    # Generate synthetic data
    np.random.seed(0)
    num_samples = 1000
    num_features = 2
    num_components = 3
    data = np.random.randn(num_samples, num_features)
    data[:300] += np.array([3, 3])
    data[300:600] += np.array([-3, 3])
    data[600:] += np.array([0, -3])
    
    # Apply EM algorithm
    gmm = GaussianMixture(n_components=num_components, max_iter=100)
    gmm.fit(data)

    print("Means:")
    print(gmm.means_)
    print("\nCovariances:")
    print(gmm.covariances_)
    print("\nMixing Coefficients:")
    print(gmm.weights_)


Means:
[[-2.95308906  2.96314961]
 [-0.03691213 -2.97421608]
 [ 2.90101528  2.97575985]]

Covariances:
[[[ 0.84045761  0.01124956]
  [ 0.01124956  0.92214493]]

 [[ 0.94018923 -0.03985231]
  [-0.03985231  0.98174498]]

 [[ 1.05882055  0.00353871]
  [ 0.00353871  0.98939966]]]

Mixing Coefficients:
[0.29836119 0.40032107 0.30131774]
